### ISSUE TITLE
Add a linter

### ISSUE THREAD

**Issue by leahriffell** [tomo-riff-raff/tomo_api#30]
.rubocop.yml: 

```
require: rubocop-rails
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - './*'
    - 'app/controllers/graphql_controller.rb'
    - 'spec/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
```
